apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-dzcsqero
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-dzcsqero:9208f83b8edbee4d396f88e9b2735750a8f68f0b@sha256:4d32ac1035246f95dbf8947de48d04d4a56fab48f97b344f1e05f4d7f46db305
          name: container-image
